imports:
- { resource: 'parameters.yaml' }
- { resource: 'services.yaml' }

parameters:
    routes.dir: '../config'
    routes.file: 'routes.yaml'

services:
    kernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments:
        - '@kernel.event_dispatcher'
        - '@kernel.controller.controller_resolver'
        - '@http.request_stack'
        - '@kernel.controller.argument_resolver'

    http.request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack

    kernel.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
        -   method: addSubscriber
            arguments:
            - '@kernel.event_listener.routes_listener'
        -   method: addSubscriber
            arguments:
            - '@kernel.event_listener.exception_listener'
        -   method: addListener
            arguments:
            - "kernel.request"
            - [ "@kernel.event_listener.json_request_transformer", "onKernelRequest" ]

    kernel.event_listener.routes_listener:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
        - '@routes.router'
        - '@http.request_stack'

    kernel.event_listener.exception_listener:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
        - 'Framework\Controller\ErrorController::handleException'

    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener

    kernel.controller.argument_resolver:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

    kernel.controller.controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ContainerControllerResolver
        arguments:
            - '@service_container'

    # routing

    routes.file_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
        - '%routes.dir%'

    routes.yaml_loader:
        class: Symfony\Component\Routing\Loader\YamlFileLoader
        arguments:
        - '@routes.file_locator'

    routes.request_context:
        class: Symfony\Component\Routing\RequestContext

    routes.router:
        class: Symfony\Component\Routing\Router
        arguments:
        - '@routes.yaml_loader'
        - '%routes.file%'
        - [ ]
        - '@routes.request_context'
