imports:
- { resource: 'parameters.yaml' }
- { resource: 'services.yaml' }

parameters:
    routes.config.dir: '%config_dir%'
    routes.config.file: 'routes.yaml'
    security.config.dir: '%config_dir%'
    security.config.file: 'security.yaml'
    doctrine.orm.entities_path: '../src/App/Entity'

services:
    kernel:
        public: true
        class: Framework\Kernel
        arguments:
        - '@kernel.event_dispatcher'
        - '@kernel.controller.controller_resolver'
        - '@http.request_stack'
        - '@kernel.controller.argument_resolver'
        calls:
        -   method: registerDoctrineTypes
        -   method: enableDoctrineCache
            arguments:
            - '@doctrine.cache.factory'
            - '@doctrine.orm.configuration'

    http.request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack

    kernel.event_dispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
        -   method: addSubscriber
            arguments:
            - '@kernel.event_listener.routes_listener'
        -   method: addSubscriber
            arguments:
            - '@kernel.event_listener.exception_listener'
        -   method: addListener
            arguments:
            - "kernel.request"
            - [ "@kernel.event_listener.json_request_transformer", "onKernelRequest" ]
        -   method: addListener
            arguments:
            - "kernel.request"
            - [ "@security.firewall", "onKernelRequest" ]

    kernel.event_listener.routes_listener:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
        - '@routes.router'
        - '@http.request_stack'

    kernel.event_listener.exception_listener:
        class: Symfony\Component\HttpKernel\EventListener\ExceptionListener
        arguments:
        - 'Framework\Controller\ErrorController::handleException'

    kernel.event_listener.json_request_transformer:
        class: Qandidate\Common\Symfony\HttpKernel\EventListener\JsonRequestTransformerListener

    kernel.controller.argument_resolver:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

    kernel.controller.controller_resolver:
        class: Symfony\Component\HttpKernel\Controller\ContainerControllerResolver
        arguments:
        - '@service_container'

    # routing

    routes.file_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
        - '%routes.config.dir%'

    routes.yaml_loader:
        class: Symfony\Component\Routing\Loader\YamlFileLoader
        arguments:
        - '@routes.file_locator'

    routes.request_context:
        class: Symfony\Component\Routing\RequestContext

    routes.router:
        class: Symfony\Component\Routing\Router
        arguments:
        - '@routes.yaml_loader'
        - '%routes.config.file%'
        - [ ]
        - '@routes.request_context'

    # security

    security.firewall:
        class: Symfony\Component\Security\Http\Firewall
        arguments:
        - '@security.firewall_map'
        - '@kernel.event_dispatcher'

    security.firewall_map:
        class: Symfony\Component\Security\Http\FirewallMap
        factory: [ 'Framework\Security\FirewallMapFactory', fromRoutes ]
        arguments:
        - '%security.config.file%'
        - '@security.file_locator'
        - '@security.authentication_listener'

    security.authentication_listener:
        class: Framework\Security\AuthenticationListener

    security.request_matcher:
        class: Symfony\Component\HttpFoundation\RequestMatcher
        arguments:
        - '^/recipes/'

    security.file_locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
        - '%security.config.dir%'

    # doctrine

    doctrine.dbal.configuration:
        class: Doctrine\DBAL\Configuration

    doctrine.connection:
        class: Doctrine\DBAL\Connection
        factory: ['Doctrine\DBAL\DriverManager', getConnection]
        arguments:
        -   host: '%database.hostname%'
            user: '%database.username%'
            dbname: '%database.dbname%'
            password: '%database.password%'
            port: '%database.port%'
            driver: '%database.driver%'
        - '@doctrine.dbal.configuration'

    doctrine.orm.configuration:
        class: Doctrine\ORM\Configuration
        factory: ['Doctrine\ORM\Tools\Setup', createAnnotationMetadataConfiguration]
        arguments:
        - ['%doctrine.orm.entities_path%']
        - '%debug%'

    doctrine.orm.entity_manager:
        class: Doctrine\ORM\EntityManager
        factory: ['Doctrine\ORM\EntityManager', create]
        arguments:
        - '@doctrine.connection'
        - '@doctrine.orm.configuration'

    # cache

    cache.predis:
        class: Predis\Client
        arguments:
        -   scheme: 'tcp'
            host: '%redis.hostname%'
            port: '%redis.port%'

    doctrine.cache.driver:
        class: Doctrine\Common\Cache\PredisCache
        arguments: [ '@cache.predis' ]

    doctrine.cache.configuration:
        class: Doctrine\ORM\Cache\CacheConfiguration

    doctrine.cache.regions_configuration:
        class: Doctrine\ORM\Cache\RegionsConfiguration

    doctrine.cache.factory:
        class: Doctrine\ORM\Cache\DefaultCacheFactory
        arguments:
        - '@doctrine.cache.regions_configuration'
        - '@doctrine.cache.driver'
