parameters:
    routes.dir: '../config'
    routes.file: 'routes.yaml'

services:
    Symfony\Component\HttpKernel\HttpKernel:
        class: Symfony\Component\HttpKernel\HttpKernel
        arguments:
            - '@Symfony\Component\EventDispatcher\EventDispatcher'
            - '@Symfony\Component\HttpKernel\Controller\ControllerResolver'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@Symfony\Component\HttpKernel\Controller\ArgumentResolver'

    Symfony\Component\HttpFoundation\RequestStack:
        class: Symfony\Component\HttpFoundation\RequestStack

    Symfony\Component\EventDispatcher\EventDispatcher:
        class: Symfony\Component\EventDispatcher\EventDispatcher
        calls:
            - method: addSubscriber
              arguments:
              - '@routes.listener'

    Symfony\Component\HttpKernel\Controller\ArgumentResolver:
        class: Symfony\Component\HttpKernel\Controller\ArgumentResolver

    Symfony\Component\HttpKernel\Controller\ControllerResolver:
        class: Symfony\Component\HttpKernel\Controller\ControllerResolver

    routes.locator:
        class: Symfony\Component\Config\FileLocator
        arguments:
            - '%routes.dir%'

    routes.loader:
        class: Symfony\Component\Routing\Loader\YamlFileLoader
        arguments:
            - '@routes.locator'

    routes.request_context:
        class: Symfony\Component\Routing\RequestContext

    routes.router:
        class: Symfony\Component\Routing\Router
        arguments:
            - '@routes.loader'
            - '%routes.file%'
            - [ ]
            - '@routes.request_context'

    routes.request_stack:
        class: Symfony\Component\HttpFoundation\RequestStack

    routes.listener:
        class: Symfony\Component\HttpKernel\EventListener\RouterListener
        arguments:
            - '@routes.router'
            - '@routes.request_stack'
