recipes_list:
    path: /recipes
    controller: 'app.controller.recipe::listAction'
    methods: [GET]

recipes_create:
    path: /recipes
    controller: 'app.controller.recipe::createAction'
    methods: [POST]

recipes_get:
    path: /recipes/{id}
    controller: 'app.controller.recipe::getAction'
    methods: [GET]
    requirements:
        id: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

recipes_update:
    path: /recipes/{id}
    controller: 'app.controller.recipe::updateAction'
    methods: [PUT, PATCH]
    requirements:
        id: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

recipes_delete:
    path: /recipes/{id}
    controller: 'app.controller.recipe::deleteAction'
    methods: [DELETE]
    requirements:
        id: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

recipes_rate:
    path: /recipes/{id}/rating
    controller: 'app.controller.recipe::rateAction'
    methods: [POST]
    requirements:
        id: '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'

recipes_search:
    path: /recipes/search
    controller: 'app.controller.recipe::searchAction'
    methods: [POST]
