services:
    app.controller.recipe:
        class: App\Controller\RecipeController
        arguments:
            - '@app.service.recipe_manager'

    app.service.recipe_manager:
        class: App\Service\RecipeManager